/**
 * Tews6PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package tews6.wsdl;

public interface Tews6PortType extends java.rmi.Remote {
    public tews6.wsdl.ObjectsFeederSearchResult objectsFeederSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ObjectsFeederSearch objectsFeederSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus objectsFeeder(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ObjectsFeeder objectsFeederPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ObjectsFeederQueryResult objectsFeederQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ObjectsFeederQuery objectsFeederQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus changeMyPassword(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ChangeMyPassword changeMyPasswordPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ChangeMyPasswordQueryResult changeMyPasswordQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ChangeMyPasswordQuery changeMyPasswordQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus correlationAttributeConfiguration(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.CorrelationAttributeConfiguration correlationAttributeConfigurationPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.CorrelationAttributeConfigurationQueryResult correlationAttributeConfigurationQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.CorrelationAttributeConfigurationQuery correlationAttributeConfigurationQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.CreateOwnerPoliciesForProvisioningRolesSearchResult createOwnerPoliciesForProvisioningRolesSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.CreateOwnerPoliciesForProvisioningRolesSearch createOwnerPoliciesForProvisioningRolesSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus createOwnerPoliciesForProvisioningRoles(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.CreateOwnerPoliciesForProvisioningRoles createOwnerPoliciesForProvisioningRolesPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.CreateOwnerPoliciesForProvisioningRolesQueryResult createOwnerPoliciesForProvisioningRolesQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.CreateOwnerPoliciesForProvisioningRolesQuery createOwnerPoliciesForProvisioningRolesQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.CreateWorkflowTemplateSearchResult createWorkflowTemplateSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.CreateWorkflowTemplateSearch createWorkflowTemplateSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus createWorkflowTemplate(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.CreateWorkflowTemplate createWorkflowTemplatePart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.DeleteWorkflowTemplateSearchResult deleteWorkflowTemplateSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.DeleteWorkflowTemplateSearch deleteWorkflowTemplateSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus deleteWorkflowTemplate(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.DeleteWorkflowTemplate deleteWorkflowTemplatePart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.DeleteWorkflowTemplateQueryResult deleteWorkflowTemplateQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.DeleteWorkflowTemplateQuery deleteWorkflowTemplateQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus templateEmployeeCreationFromFeed(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.TemplateEmployeeCreationFromFeed templateEmployeeCreationFromFeedPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus templateEmployeeSelfModification(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.TemplateEmployeeSelfModification templateEmployeeSelfModificationPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.TemplateEmployeeSelfModificationQueryResult templateEmployeeSelfModificationQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.TemplateEmployeeSelfModificationQuery templateEmployeeSelfModificationQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus inboundNotification(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.InboundNotification inboundNotificationPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.InboundNotificationQueryResult inboundNotificationQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.InboundNotificationQuery inboundNotificationQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.TemplateModifyContractorByManagerSearchResult templateModifyContractorByManagerSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.TemplateModifyContractorByManagerSearch templateModifyContractorByManagerSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus templateModifyContractorByManager(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.TemplateModifyContractorByManager templateModifyContractorByManagerPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.TemplateModifyContractorByManagerQueryResult templateModifyContractorByManagerQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.TemplateModifyContractorByManagerQuery templateModifyContractorByManagerQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ModifyUseCaseSearchResult modifyUseCaseSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ModifyUseCaseSearch modifyUseCaseSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus modifyUseCase(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ModifyUseCase modifyUseCasePart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ModifyUseCaseQueryResult modifyUseCaseQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ModifyUseCaseQuery modifyUseCaseQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ModifyWorkflowTemplateSearchResult modifyWorkflowTemplateSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ModifyWorkflowTemplateSearch modifyWorkflowTemplateSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus modifyWorkflowTemplate(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ModifyWorkflowTemplate modifyWorkflowTemplatePart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ModifyWorkflowTemplateQueryResult modifyWorkflowTemplateQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ModifyWorkflowTemplateQuery modifyWorkflowTemplateQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.OnboardAccountTabEndpointExploreSearchResult onboardAccountTabEndpointExploreSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.OnboardAccountTabEndpointExploreSearch onboardAccountTabEndpointExploreSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus onboardAccount(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.OnboardAccount onboardAccountPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ManageReportServerConnectionSearchResult manageReportServerConnectionSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ManageReportServerConnectionSearch manageReportServerConnectionSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus manageReportServerConnection(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ManageReportServerConnection manageReportServerConnectionPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ResetProvisioningRoleOwnersSearchResult resetProvisioningRoleOwnersSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ResetProvisioningRoleOwnersSearch resetProvisioningRoleOwnersSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus resetProvisioningRoleOwners(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ResetProvisioningRoleOwners resetProvisioningRoleOwnersPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ResetProvisioningRoleOwnersQueryResult resetProvisioningRoleOwnersQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ResetProvisioningRoleOwnersQuery resetProvisioningRoleOwnersQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ResetUserPasswordSearchResult resetUserPasswordSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ResetUserPasswordSearch resetUserPasswordSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus resetUserPassword(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ResetUserPassword resetUserPasswordPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ResetUserPasswordQueryResult resetUserPasswordQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ResetUserPasswordQuery resetUserPasswordQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.TransferDocumentOwnershipSearchResult transferDocumentOwnershipSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.TransferDocumentOwnershipSearch transferDocumentOwnershipSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.TransferDocumentOwnershipTabTransferDocumentOwnershipSearchResult transferDocumentOwnershipTabTransferDocumentOwnershipSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.TransferDocumentOwnershipTabTransferDocumentOwnershipSearch transferDocumentOwnershipTabTransferDocumentOwnershipSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus transferDocumentOwnership(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.TransferDocumentOwnership transferDocumentOwnershipPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.TransferDocumentOwnershipQueryResult transferDocumentOwnershipQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.TransferDocumentOwnershipQuery transferDocumentOwnershipQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ViewMyWorkListTabWorkListSearchResult viewMyWorkListTabWorkListSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ViewMyWorkListTabWorkListSearch viewMyWorkListTabWorkListSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus viewMyWorkList(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ViewMyWorkList viewMyWorkListPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ViewMyWorkListQueryResult viewMyWorkListQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ViewMyWorkListQuery viewMyWorkListQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ViewUseCaseSearchResult viewUseCaseSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ViewUseCaseSearch viewUseCaseSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ViewUseCaseQueryResult viewUseCaseQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ViewUseCaseQuery viewUseCaseQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ViewUserSearchResult viewUserSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ViewUserSearch viewUserSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ViewUserQueryResult viewUserQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ViewUserQuery viewUserQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ViewWorkflowTemplateSearchResult viewWorkflowTemplateSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ViewWorkflowTemplateSearch viewWorkflowTemplateSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ViewWorkflowTemplateQueryResult viewWorkflowTemplateQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.ViewWorkflowTemplateQuery viewWorkflowTemplateQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.PORTALObjectsFeederSearchResult PORTALObjectsFeederSearch(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.PORTALObjectsFeederSearch PORTALObjectsFeederSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.ImsStatus PORTALObjectsFeeder(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.PORTALObjectsFeeder PORTALObjectsFeederPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.PORTALObjectsFeederQueryResult PORTALObjectsFeederQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.PORTALObjectsFeederQuery PORTALObjectsFeederQueryPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
    public tews6.wsdl.TaskStatusQueryResult taskStatusQuery(tews6.wsdl.TaskContext taskContextPart, tews6.wsdl.TaskStatusSearchFilter[] taskStatusSearchPart) throws java.rmi.RemoteException, tews6.wsdl.ImsException;
}
